name: Publish release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  docker-hub:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn 
      - run: yarn build
      - name: Get tag
        id: get_tag
        shell: bash
        run: |
          tag=${GITHUB_REF/refs\/tags\//}
          echo "::set-output name=tag::$tag"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: deernetwork/deer-storage-worker:latest,deernetwork/deer-storage-worker:${{ steps.get_tag.outputs.tag }}